spring:
  application:
    name:  yuanfang-sole
  redis:
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 50 # 连接池中的最大空闲连接
        min-idle: 10 # 连接池中的最小空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 1000
      host: 127.0.0.1
      port: 6379
      database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/yuanfang?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver
    #HikariPool
    hikari:
      #最小空闲连接
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      #连接池最大连接数
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      connection-timeout: 3000
  cross:
      allow: http://localhost:9527,http://localhost:8081
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #show sql 全局配置方式
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    #show sql 单个mapper
    com.pt.zh.yuanfang.modules.*.*: debug
server:
  port: 8081